name: warnings

on:
  schedule:
    - cron: '*/13 * * * *'   # <-- Set your cron here (UTC). Uses github which can be ~2-10 mins late.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout this repo into the Github Actions runner
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache node_modules
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: "**/warnings/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Install packages if there's no cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |-
          npm ci

      - name: Start the data processing using make
        env:
          BOT_NAME: ${{ github.workflow }} # <-- This makes you bot name available to scripts
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        uses: nick-fields/retry@v2
        with:
          max_attempts: 5
          retry_on: error
          timeout_minutes: 5
          retry_wait_seconds: 30
          command: make all

      - name: Commit and push to main branch
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Updated at: ${timestamp}" || exit 0
          git push origin main
